<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Soporte;
use AppBundle\Entity\Usuario;
/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{

    public function soportesPorCliente()
    {
        $consulta = $this->getEntityManager()->createQuery(
            'SELECT u.nombre,count(s.idUsuario) total
            FROM AppBundle\Entity\Soporte s
            JOIN AppBundle\Entity\Usuario u
            WHERE s.idUsuario = u.id
            group by u.nombre
            ORDER by total DESC'
        );
            $valor = $consulta->getResult();
        return $valor;

    }

    public function soportesPorTipoSoporte()
    {
        $consulta = $this->getEntityManager()->createQuery(
            'SELECT t.nombre,count(s.idTipoSoporte) total
            FROM AppBundle\Entity\Soporte s
            JOIN AppBundle\Entity\TipoSoporte t
            WHERE s.idTipoSoporte = t.id
            group by t.nombre'
        );
            $valor = $consulta->getResult();
        return $valor;

    }

    public function listarTodo()
    {
        $consulta = $this->getEntityManager()->createQuery(
            'SELECT s.id,s.asunto,s.descripcion,s.prioridad,s.estado,s.descripcionSolucion,u.nombre as nombreUsuario,u.apellido
            FROM AppBundle\Entity\Soporte s
            JOIN AppBundle\Entity\Usuario u
            WHERE s.idUsuario = u.id'
        );
            $valor = $consulta->getResult();
        return $valor;

    }

    public function buscarSoportesCliente($idUsuario)
    {
        $consulta = $this->getEntityManager()->createQuery(
            'SELECT s.id,s.asunto,s.descripcion,s.prioridad,s.estado,s.descripcionSolucion,u.nombre,u.apellido
            FROM AppBundle\Entity\Soporte s
            JOIN AppBundle\Entity\Usuario u
            WHERE s.idUsuario = u.id
            and u.nombre= :idUsuario'
        )->setParameter('idUsuario', $idUsuario);
            $valor = $consulta->getResult();
        return $valor;

    }
    
}
